In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
type(my_list)

list

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
mylist = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
mymatrix = np.array(mylist)

In [8]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
mymatrix.shape

(3, 3)

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((5,5)) + 4

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [16]:
np.ones(4) * 100

array([100., 100., 100., 100.])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(4)

array([0.28865297, 0.14285355, 0.15725297, 0.39251746])

In [22]:
np.random.rand(5,5)

array([[0.23622527, 0.92920442, 0.89539544, 0.37552637, 0.28536321],
       [0.58823852, 0.66088423, 0.88327645, 0.93576946, 0.06138059],
       [0.63218784, 0.44904706, 0.29406976, 0.40649562, 0.69091792],
       [0.78481472, 0.92989555, 0.54548183, 0.68129239, 0.50288838],
       [0.71743435, 0.89999127, 0.12513195, 0.69007246, 0.31751127]])

In [23]:
np.random.randn(3)

array([-0.74708129,  0.35960454, -1.28184013])

In [24]:
# np.random.normal()

In [25]:
np.random.randint(1,100,10)

array([65, 47, 58, 35, 46, 18, 73, 70,  7, 67])

In [26]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
arr = np.arange(15)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [33]:
arr.shape

(15,)

In [35]:
arr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [36]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [37]:
ranarr.max()

39

In [38]:
ranarr.min()

2

In [39]:
ranarr.argmin()

9

In [40]:
ranarr.argmax()

7

In [41]:
ranarr.dtype

dtype('int64')

In [42]:
arr = np.arange(0,11)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[8]

8

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [46]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [47]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [49]:
slice_of_array = arr[1:5]

In [50]:
slice_of_array

array([1, 2, 3, 4])

In [51]:
slice_of_array[:] = 9

In [52]:
slice_of_array

array([9, 9, 9, 9])

In [53]:
arr

array([ 0,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [54]:
arr_copy = arr.copy()

In [56]:
arr_copy

array([ 0,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:] = 40

In [58]:
arr_copy

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [60]:
arr

array([ 0,  9,  9,  9,  9,  5,  6,  7,  8,  9, 10])

In [64]:
arr_2d = np.random.randint(0,101,9)

In [66]:
arr_2d.shape

(9,)

In [67]:
arr_2d.reshape(3,3)

array([[52,  1, 87],
       [29, 37,  1],
       [63, 59, 20]])

In [68]:
arr_2d[1]

1

In [70]:
arr_2d = arr_2d.reshape(3,3)

In [71]:
arr_2d

array([[52,  1, 87],
       [29, 37,  1],
       [63, 59, 20]])

In [72]:
arr_2d[1]

array([29, 37,  1])

In [73]:
arr_2d[1][1]

37

In [74]:
arr_2d[2][2]

20

In [75]:
arr_2d[2,2]

20

In [76]:
arr_2d[:2,1:]

array([[ 1, 87],
       [37,  1]])

In [77]:
try_arr = np.arange(1,11)

In [78]:
try_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
try_arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
bool_arr = try_arr > 4

In [81]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [83]:
try_arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
try_arr[try_arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [85]:
num_arr = np.arange(0,10)

In [86]:
num_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
num_arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
num_arr / num_arr

/home/sirivasv/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [89]:
1 / num_arr

/home/sirivasv/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [90]:
np.sqrt(num_arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [92]:
np.log(num_arr)

/home/sirivasv/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [93]:
np.sin(num_arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [94]:
arr.sum()

81

In [97]:
arr_2d = np.arange(1,13)

In [98]:
arr_2d = arr_2d.reshape(3,4)

In [99]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])