In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
x.dtype

torch.int32

In [13]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4, 3)

In [14]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [15]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [17]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [18]:
arr[0]

1

In [19]:
arr[0] = 99
arr

array([99,  2,  3,  4,  5])

In [20]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [22]:
my_arr = np.arange(0, 10)

In [23]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_tensor = torch.tensor(my_arr)

In [25]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [26]:
my_other_tensor = torch.from_numpy(my_arr)

In [27]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
my_arr[0]

0

In [29]:
my_arr[0] = 999
my_arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [30]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [31]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [32]:
new_arr = np.array([1, 2, 3])

In [33]:
new_arr.dtype

dtype('int32')

In [34]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [36]:
my_tensor = torch.Tensor(new_arr)
my_tensor, my_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [37]:
my_tensor = torch.FloatTensor(new_arr)
my_tensor, my_tensor.dtype

(tensor([1., 2., 3.]), torch.float32)

In [39]:
torch.empty(4,2)

tensor([[1.6615e+22, 2.5838e-06],
        [1.7473e-04, 2.7598e-06],
        [4.2112e-11, 7.1450e+31],
        [1.6534e+19, 3.0478e+32]])

In [40]:
torch.zeros(4, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [41]:
torch.zeros(4, 3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [42]:
torch.ones(4, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [43]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [44]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [45]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

In [46]:
my_tensor = torch.tensor([1, 2, 3])
my_tensor.dtype

torch.int64

In [47]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [48]:
torch.rand(4, 3)

tensor([[0.2045, 0.2333, 0.6096],
        [0.2171, 0.6568, 0.0872],
        [0.5994, 0.7997, 0.1724],
        [0.0222, 0.2379, 0.2447]])

In [49]:
torch.randn(4, 3)

tensor([[-0.0927, -1.0933, -1.4409],
        [-0.4980,  0.1902,  0.1568],
        [ 1.5564, -1.4520, -0.3468],
        [-0.6027,  0.7976,  1.0706]])

In [50]:
torch.randint(low=0, high=10, size=(5, 5))

tensor([[7, 5, 9, 8, 8],
        [2, 8, 0, 6, 1],
        [1, 5, 9, 3, 2],
        [8, 0, 1, 4, 1],
        [4, 1, 7, 2, 4]])

In [51]:
x = torch.zeros(2, 5)

In [52]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [53]:
x.shape

torch.Size([2, 5])

In [54]:
torch.rand_like(x)

tensor([[0.2459, 0.4388, 0.7385, 0.3137, 0.5009],
        [0.6459, 0.6980, 0.5848, 0.5473, 0.3081]])

In [55]:
torch.randn_like(x)

tensor([[ 0.9871, -1.3453, -0.3689,  0.5362,  0.4861],
        [-1.3529, -0.7999, -2.7182, -0.6976,  0.6213]])

In [56]:
torch.randint_like(x, low=0, high=11)

tensor([[0., 3., 1., 0., 7.],
        [0., 2., 2., 8., 9.]])

In [61]:
torch.manual_seed(42)
torch.rand(2, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])