In [1]:
import torch
import numpy as np

In [4]:
x = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
x[1, 1], type(x[1, 1])

(tensor(3), torch.Tensor)

In [10]:
x[:, 1]

tensor([1, 3, 5])

In [11]:
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [15]:
x = torch.arange(0,10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x = x.reshape(2, 5)

In [26]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
x = torch.arange(10)

In [28]:
x.shape

torch.Size([10])

In [29]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
z = x.view(2, 5)

In [32]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
x[0] = 99999

In [34]:
x

tensor([99999,     1,     2,     3,     4,     5,     6,     7,     8,     9])

In [35]:
z

tensor([[99999,     1,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

In [37]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x.shape

torch.Size([10])

In [39]:
# INFER what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [40]:
x.view(-1,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [41]:
a = torch.tensor([1., 2., 3.])
b = torch.tensor([4., 5., 6.])

In [42]:
a

tensor([1., 2., 3.])

In [43]:
a.dtype

torch.float32

In [44]:
b

tensor([4., 5., 6.])

In [45]:
a + b

tensor([5., 7., 9.])

In [46]:
torch.add(a, b)

tensor([5., 7., 9.])

In [47]:
a.mul(b)

tensor([ 4., 10., 18.])

In [48]:
a

tensor([1., 2., 3.])

In [49]:
a.mul_(b)

tensor([ 4., 10., 18.])

In [50]:
a

tensor([ 4., 10., 18.])

In [51]:
a = torch.tensor([1., 2., 3.])
a

tensor([1., 2., 3.])

In [52]:
b

tensor([4., 5., 6.])

In [53]:
a * b

tensor([ 4., 10., 18.])

In [54]:
a.mul(b)

tensor([ 4., 10., 18.])

In [55]:
a.dot(b)

tensor(32.)

In [57]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [58]:
b = torch.tensor([[6, 7], [8, 9], [10, 11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [59]:
a.shape

torch.Size([2, 3])

In [60]:
b.shape

torch.Size([3, 2])

In [61]:
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

In [62]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [63]:
x = torch.tensor([2., 3., 4., 5.])
x

tensor([2., 3., 4., 5.])

In [64]:
x.norm()

tensor(7.3485)

In [66]:
x.numel()

4

In [68]:
len(x)

4

In [69]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [70]:
len(a)

2

In [72]:
a.numel()

6